service: aws-node-reto-backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:* 
      Resource:
        - arn:aws:dynamodb:us-east-1:${aws:accountId}:table/StarWarsPersonTable

functions:
  createStarWarsPeople:
    handler: src/index.createStarWarsPerson
    events:
      - httpApi:
          path: /starWarsPeople
          method: post
  getStarWarsPerson:
    handler: src/index.getStarWarsPerson
    events:
      - httpApi:
          path: /starWarsPeople/{id}
          method: get
          
resources: 
  Resources:
    StarWarsPersonTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: StarWarsPersonTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
